apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend
  labels:
    app: {{ .Chart.Name }}-backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
  - port: {{ .Values.service.backend.port }}
    targetPort: {{ .Values.service.backend.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Chart.Name }}-backend
