apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend
  labels:
    app: {{ .Chart.Name }}-frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
  - port: {{ .Values.service.frontend.port }}
    targetPort: {{ .Values.service.frontend.targetPort }}
    nodePort: {{ .Values.service.frontend.nodePort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Chart.Name }}-frontend
